### ISSUE TITLE
Monitoring/waiting for job completion

### ISSUE THREAD

**Issue by jacobdanovitch** [amq92/simple-slurm#1]
Does this package support anything like this?

```python
slurm.sbatch('python demo.py ' + Slurm.SLURM_ARRAY_JOB_ID)
slurm.wait_for_completion()
```

If not, I might be interested in contributing a bit.

**Comment by amq92** [comment]
In short, it does not. But I think it can easily be accomplished !

If I understand correctly the goal here is to execute some code after a job has been submitted (possibly profiting from its results).

```python
slurm = Slurm(**opts)
slurm.sbatch('python demo.py')
slurm.wait_for_completion()

print('do something')
```

In such case, a possible workaround would be to place the subsequent code in another file and launch the job with a dependency to the first one. **The `sbatch` call returns the job_id _(added it to the documentation)_**

```python
slurm = Slurm(**opts)
job_id = slurm.sbatch('python demo.py')

slurm_after = Slurm(**opts, dependency=dict(afterok=job_id))
slurm_after.sbatch('python demo_after.py') 
```

However, if the goal is to freeze the execution of the current code, your contribution would be appreciated.
I suppose that this can be achieved by adapting the call from `sbatch` to `srun`  (however no array jobs supported).

**Comment by jacobdanovitch** [comment]
Oops, I missed the notification for your reply to this. It seems that sbatch supports a `--wait` directive that does precisely this, though it wouldn't show stdout the way srun would. I can take a look at using that directive vs. an srun-based alternative if I have some time in the next couple weeks.

**Comment by jacobdanovitch** [comment]
Added a PR using a simple `srun` based alternative. The method is only 3 lines, didn't refactor anything aside from moving stdout piping to a keyword argument provided by `sbatch`.
