### ISSUE TITLE
Shell hashbang option

### ISSUE THREAD

**Issue by murnanedaniel** [amq92/simple-slurm#3]
It would be great if one could submit a batch job with a hashbang other than `.../sh`, e.g. `.../bash`. Perhaps this could added as a run config? Something like `slurm.sbatch(run commands, shell="bash")`.

**Comment by amq92** [comment]
Good idea! `slurm.sbatch(*args, shell='/bin/sh')` is now the default behavior.
closed in 4ef1cd4
