### ISSUE TITLE
job_id fails to return when using clusters

### ISSUE THREAD

**Issue by AlecThomson** [amq92/simple-slurm#4]
Hi there,

It's possible to set a 'cluster' option in Slurm:
```
#SBATCH --clusters            {my_cluster_name}
```
From Slurm docs:

> -M, --clusters=<string>
> Clusters to issue commands to. Multiple cluster names may be comma separated. The job will be submitted to the one cluster providing the earliest expected job initiation time. The default value is the current cluster. A value of 'all' will query to run on all clusters. Note the --export option to control environment variables exported between clusters. Note that the SlurmDBD must be up for this option to work properly.
> 

When doing this, the return message will be:
Submitted batch job {job_ID} on cluster {my_cluster_name}

This causes a ValueError in simple-slurm at the moment:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-17-d58e7c3efb9b> in <module>
----> 1 slurm.sbatch(cmd)

simple_slurm/core.py in sbatch(self, run_cmd, convert, sbatch_cmd, shell)
    145         stdout = result.stdout.decode('utf-8')
    146         assert success_msg in stdout, result.stderr
--> 147         job_id = int(stdout.replace(success_msg, ''))
    148         print(success_msg, job_id)
    149         return job_id

ValueError: invalid literal for int() with base 10: ' {job_ID} on cluster {my_cluster_name}\n'
```
I think this would be fairly easy to catch with some additional string parsing

**Comment by amq92** [comment]
Sure! 7814ec8 should fix it
